CERTIFICATE_DIRECTORY_ROOT ?= vendor/nitrogen/signatures
CERTIFICATE_COMMON := $(CERTIFICATE_DIRECTORY_ROOT)/common

ifeq ($(TARGET_BUILD_FULLY_SIGN),true)
NITROGEN_AVB_KEY_PATH := $(CERTIFICATE_COMMON)/data/releasekey.pk8
endif
